name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Dagger
        uses: kpenfound/dagger-action@main
        with:
          args: ci-remote --commit $GITHUB_SHA
          module: github.com/kpenfound/greetings-api/ci
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
